const CONTENT = {
    images: [
        // require('./../images/m001.jpg'),
        // require('./../images/m002.jpg'),
        // require('./../images/m003.jpg'),
        // require('./../images/m004.jpg'),
        // require('./../images/m005.jpg'),
        // require('./../images/m006.jpg'),
        // require('./../images/m007.jpg'),
        // require('./../images/m008.jpg'),
        // require('./../images/m009.jpg'),
        // require('./../images/m010.jpg'),
        require('./../images/001.PNG'),
        // require('./../images/002.PNG'),
        // require('./../images/003.PNG'),
        // require('./../images/004.PNG'),
        // require('./../images/005.PNG'),
        // require('./../images/006.PNG'),
        // require('./../images/007.PNG'),
        // require('./../images/008.PNG'),
        // require('./../images/009.PNG'),
        // require('./../images/010.PNG'),
        // require('./../images/011.PNG'),
        // require('./../images/012.PNG'),
        // require('./../images/013.PNG'),
        // require('./../images/014.PNG'),
        // require('./../images/015.PNG'),
        // require('./../images/016.PNG'),
        // require('./../images/017.PNG'),
        // require('./../images/018.PNG'),
        // require('./../images/019.PNG'),
        // require('./../images/020.PNG'),
        // require('./../images/021.PNG'),
        // require('./../images/022.PNG'),
        // require('./../images/023.PNG'),
        // require('./../images/024.PNG'),
        // require('./../images/025.PNG'),
        // require('./../images/026.PNG'),
        // require('./../images/027.PNG'),
    ]
}

export default CONTENT